name: Deploy to Cloudflare Pages

on:
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build  

      - name: Deploy to Cloudflare Pages
        run: |
          npx wrangler pages publish ./dist  
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}






