name: Deploy to Cloudflare Workers and Run Nuxt

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install Node.js dependencies
      - name: Install Dependencies
        run: npm install

      # Build Nuxt application
      - name: Build Nuxt Application
        run: npm run build

      # Deploy to Cloudflare Workers
      - name: Deploy to Cloudflare Workers
        run: npm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}


